//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvProjesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_skill
    {
        public int SkillID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string SkillName { get; set; }
        public string ProficiencyLevel { get; set; }
    
        public virtual tbl_user tbl_user { get; set; }
    }
}
